In [ ]:
import numpy as np

NumPy Search

In [ ]:
#Search for a particular element

arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

y = np.where(arr%2 == 0)
print(y)

(array([3, 5, 6]),)
(array([1, 3, 5, 6]),)


In [ ]:
# searchsorted() - Sorts array and returns 
#index of insertion for a particular element

arr = np.array([6, 7, 18, 29])

x = np.searchsorted(arr, 19)
print(x) 

y = np.searchsorted(arr, [1, 12, 42])
print(y)

3
[0 2 4]


NumPy Array Slicing

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print(arr[4:])
print(arr[:4])

[2 3 4 5]
[5 6 7]
[1 2 3 4]


In [ ]:
# -ve slice takes values from the back
# can add step value [::step]

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-4:-1])
print(arr[1:5:2])
print(arr[::2]) 

[4 5 6]
[2 4]
[1 3 5 7]


In [ ]:
# For 2D Arrays

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10],[11,12,13,14,15]])

print(arr[1,1:4])
print(arr[2,0:2])
print(arr[0:3, 2]) #from both elements of array, returns value at index 2
print(arr[0:2, 1:4]) 

[7 8 9]
[11 12]
[ 3  8 13]
[[2 3 4]
 [7 8 9]]


NumPy Split

In [ ]:
# splitting 1D array

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)
print(newarr[0])
print(newarr[1])
print(newarr[2])
print(newarr)

[1 2]
[3 4]
[5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
# splitting 2D array

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)
print(newarr[0])
print("\n")
print(newarr[1])
print("\n")
print(newarr[2]) 

[[1 2]
 [3 4]]


[[5 6]
 [7 8]]


[[ 9 10]
 [11 12]]


In [ ]:
# Can split 2D array without perfect division. The array_split() func 
# splits an array into multiple sub-arrays of equal or near-equal size. 
# Does not raise an exception if an equal division cannot be made.

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 4)
print("\n")
print(newarr[0])
print("\n")
print(newarr[1])
print("\n")
print(newarr[2])



[[1 2]
 [3 4]]


[[5 6]
 [7 8]]


[[ 9 10]]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr[0])
print("\n")
print(newarr[1])
print("\n")
print(newarr[2])

[[1 2 3]
 [4 5 6]]


[[ 7  8  9]
 [10 11 12]]


[[13 14 15]
 [16 17 18]]


In [ ]:
#splitting with axis=1, returns first element from all sub-arrays

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr[0])
print("\n")
print(newarr[1])
print("\n")
print(newarr[2])

[[ 1]
 [ 4]
 [ 7]
 [10]
 [13]
 [16]]


[[ 2]
 [ 5]
 [ 8]
 [11]
 [14]
 [17]]


[[ 3]
 [ 6]
 [ 9]
 [12]
 [15]
 [18]]


In [ ]:
# hsplit()

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)
print(newarr[0])
print("\n")
print(newarr[1])
print("\n")
print(newarr[2])

[[ 1]
 [ 4]
 [ 7]
 [10]
 [13]
 [16]]


[[ 2]
 [ 5]
 [ 8]
 [11]
 [14]
 [17]]


[[ 3]
 [ 6]
 [ 9]
 [12]
 [15]
 [18]]


In [ ]:
# vsplit()

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.vsplit(arr, 3)
print(newarr[0])
print("\n")
print(newarr[1])
print("\n")
print(newarr[2])

[[1 2 3]
 [4 5 6]]


[[ 7  8  9]
 [10 11 12]]


[[13 14 15]
 [16 17 18]]


NumPy Concatenate and Stack

In [ ]:
# 1D array concatenation

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr) 

[1 2 3 4 5 6]


In [ ]:
# 2D array concatenation

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print("arr1=\n", arr1) 
print("\narr2=\n", arr2) 

arr = np.concatenate((arr1, arr2), axis=1) #0=row, 1=col
print("\nafter concatenation where axis=1 =\n",arr)

arr = np.concatenate((arr1, arr2), axis=0) #0=row, 1=col
print("\nafter concatenation where axis=0 =\n",arr)

arr1=
 [[1 2]
 [3 4]]

arr2=
 [[5 6]
 [7 8]]

after concatenation where axis=1 =
 [[1 2 5 6]
 [3 4 7 8]]

after concatenation where axis=0 =
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
# Concatenate using Transpose

a= np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[10,11,12]])
print(np.concatenate((a, b.T), axis=1)) #Take transpose of b

[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


In [ ]:
# 1D array hstack and vstack

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))
print("hstack()=\n",arr)

arr = np.vstack((arr1, arr2))
print("\nvstack()=\n",arr)

hstack()=
 [1 2 3 4 5 6]

vstack()=
 [[1 2 3]
 [4 5 6]]


In [ ]:
# 2D array hstack and vstack

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print("hstack =\n", np.hstack((a,b)))
print("\nvstack =\n", np.vstack((a,b)))

hstack =
 [[1 2 5 6]
 [3 4 7 8]]

vstack =
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
# append 2D array

a= np.array([[1, 2, 3], [4, 5, 6]])
print(a)
b = np.array([[7,8,9]])
print("\n",b)
print("\n",np.append(a,b, axis=0))

[[1 2 3]
 [4 5 6]]

 [[7 8 9]]

 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# np.r_ - Translates slice objects to concatenation along the first axis.
# This is a simple way to build up arrays quickly

a = np.array([1,2,3])
b = np.array([5,6])
print(np.r_[a,b])
print(np.r_[a[0:2],b[0]])

[1 2 3 5 6]
[1 2 5]


In [ ]:
# stack and reshape

a = np.array([1,2,3])
b = np.array([5,6,7])
print(np.stack([a,b]))
print("\n",np.stack([a,b]).reshape(-1))

[[1 2 3]
 [5 6 7]]

 [1 2 3 5 6 7]


In [ ]:
a = np.array((1,2,3))
b = np.array((7,8,9))
print(a)
print(b)

print("\nvstack")
print(np.vstack((a,b)))
print("\nconcatenate")
print(np.concatenate([a.reshape(1,3),b.reshape(1,3)]))
print("\nstack")
print(np.stack((a,b),axis=1))
print("\nconcatenate")
print(np.concatenate((a.reshape(1,3),b.reshape(1,3)),axis = 1))
print("\nstack")
print(np.stack((a,b),axis=0))
print("\nconcatenate")
print(np.concatenate((a.reshape(1,3),b.reshape(1,3)),axis = 0))

[1 2 3]
[7 8 9]

vstack
[[1 2 3]
 [7 8 9]]

concatenate
[[1 2 3]
 [7 8 9]]

stack
[[1 7]
 [2 8]
 [3 9]]

concatenate
[[1 2 3 7 8 9]]

stack
[[1 2 3]
 [7 8 9]]

concatenate
[[1 2 3]
 [7 8 9]]
